# .github/workflows/publish.yml
name: Publish

on:
  push:
    tags:
      - "v*"

jobs:
  pypi:
    runs-on: ubuntu-latest
    environment: pypi           # gates this job behind environment approval
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v5

      - name: Install uv
        uses: astral-sh/setup-uv@v6

      - name: Set up Python
        run: uv python install 3.13

      - name: Build distributions
        run: uv build

      # optional smoke checks that the wheel/sdist are usable
      - name: Smoke test (wheel)
        run: uv run --isolated --no-project --with dist/*.whl -c "import sys; print('ok')"
      - name: Smoke test (sdist)
        run: uv run --isolated --no-project --with dist/*.tar.gz -c "import sys; print('ok')"

      - name: Publish to PyPI
        run: uv publish
